version: '3.3'

services:
   db:
     image: mysql:5.7
     restart: always
     environment:
       MYSQL_DATABASE: 'mydb'
       # So you don't have to use root, but you can if you like
       MYSQL_USER: 'usr'
       # You can use whatever password you like
       MYSQL_PASSWORD: 'pwd'
       # Password for root access
       MYSQL_ROOT_PASSWORD: 'password'
     ports:
       # <Port exposed> : < MySQL Port running inside container>
       - '3306:3306'
     expose:
      # Opens port 3306 on the container
       - '3306'
       # Where our data will be persisted
     volumes:
       - my-db:/var/lib/mysql

   app:
     depends_on:
       - db
     build: .
     ports:
       - "8000:8080"
     restart: always
volumes:
  my-db:
